### ISSUE TITLE
Help with CustomCell + BWSwipeRevealCell

### ISSUE THREAD

**Issue by AnnieNinaJoyceV** [bitwit/BWSwipeRevealCell#6]
I created a CustomCell that I subclassed from BWSwipeRevealCell. And in the ViewController's `cellForRowAtIndexPath` I have these lines added:

`let swipeCell:BWSwipeRevealCell = cell as! BWSwipeRevealCell`
`swipeCell.bgViewRightImage = UIImage(named:"delete_icon")!.imageWithRenderingMode(.AlwaysTemplate)`
`swipeCell.bgViewRightColor = UIColor.redColor()`
`swipeCell.type = .SlidingDoor`
`swipeCell.delegate = self`
`return swipeCell`

I see the Right View but it is not triggering any action. The `swipeCellActivatedAction` method is never called. It would be helpful if you can provide any solutions/workarounds.

**Comment by bitwit** [comment]
Hey, thanks for giving this pod a shot!

I'm curious to know what protocol your delegate is implementing. Are you using `BWSwipeRevealCellDelegate` (correct for this use case) , or `BWSwipeCellDelegate` (wrong for htis use case)

`BWSwipeRevealCellDelegate` is a protocol that extends from `BWSwipeCellDelegate` to implement the one additional `swipeCellActivatedAction` method.

If that's not the issue let me know

**Comment by AnnieNinaJoyceV** [comment]
That's correct. I hadn't set BWSwipeRevealCellDelegate. Very silly mistake :)
Its a wonderful pod, thanks for sharing.

**Comment by bitwit** [comment]
Awesome, glad it worked! :+1:
