### ISSUE TITLE
Swift 3.0 support

### ISSUE THREAD

**Issue by bitwit** [bitwit/BWSwipeRevealCell#8]
Make sure that the code is Swift 3.0 ready and adjust the APIs in accordance with rules outlined in the WWDC 2016 Swift API Guidelines

https://developer.apple.com/videos/play/wwdc2016/403/

**Comment by bitwit** [comment]
Looks like Swift 3.0 is not going to be prime time ready, so this will probably be delayed and Swift 2.3 supported instead

**Comment by lfarah** [comment]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by bitwit** [comment]
Given I have a PR for just swift 3.0 support to review here: https://github.com/bitwit/BWSwipeRevealCell/pull/12 I may end up implementing it sooner than I expected before adding collectionview support in a future release.

Stay tuned!

**Comment by bitwit** [comment]
`2.0.0` now released
